# Generated by Django 2.0.2 on 2018-02-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=50, null=True)),
                ('relatedProcessed', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('g', 'google'), ('y', 'youtube')], default='g', max_length=1)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='RelatedQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('text',),
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('processed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WebsiteTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('t', 'title'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('l', 'li'), ('im', 'Image Title'), ('al', 'Image Alternate Text'), ('b', 'Bold'), ('it', 'Italic'), ('u', 'Underlined')], default='h1', max_length=2)),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('-count',),
            },
        ),
        migrations.AddField(
            model_name='website',
            name='tags',
            field=models.ManyToManyField(to='fetcher.WebsiteTags'),
        ),
        migrations.AddField(
            model_name='query',
            name='related',
            field=models.ManyToManyField(to='fetcher.RelatedQuery'),
        ),
        migrations.AddField(
            model_name='query',
            name='websites',
            field=models.ManyToManyField(to='fetcher.Website'),
        ),
    ]
